### ISSUE TITLE
[Qt6.8] Nero complains about "Current Runner not found" and creates a new prefix with an & symbol in the name

### ISSUE THREAD

**Issue by TimeFreeze1337** [SeongGino/Nero-umu#30]
I start Nero create a new prefix name it whatever, i go inside the prefix and Nero complains:

![Screenshot_20241204_205015](https://github.com/user-attachments/assets/69927ae4-0346-4717-a0ee-1486da3ea921)

I'll take a look inside the Prefix folder which i created for Nero and now there are 2 or more prefixes with an & symbol in the name.

![Screenshot_20241204_205545](https://github.com/user-attachments/assets/df6f23b0-8e21-49e1-b969-261a1911acfa)

Opening Nero via the terminal and doing the exact steps i get this output:

![Screenshot_20241205_094822](https://github.com/user-attachments/assets/c8c8f665-47c6-4ce6-88df-e5029873db71)

Quick side note: It also seems that Nero has problems deleting the original prefix after this issue happens since after i delete all 3 for example the "original" prefix remains, but not visible in Nero unless i restart it. And if i go inside that prefix then the issue repeats with Current Runner not found and creating a new prefix with the same name and an & symbol inside of it.

The runner list includes those: 

![Screenshot_20241205_095611](https://github.com/user-attachments/assets/409fffc9-39f5-4dc9-a37c-e680502145f4)

And no matter what i choose: proton-tkg, GE-Proton or UMU-Latest it still happens.

Also i already said it on Discord but just in case: Nero's own dir "~/.local/share/Nero-UMU/compatibilitytools.d" does not exist. Not sure if thats supposed to be or if that dir should have been created when starting Nero but i just wanted to point it out.

**Comment by SeongGino** [comment]
Discord is a non-entity in GitHub, so please remember to provide appropriate context in issues regardless of where the conversation originally started, thank you.

Usually the bits about "Application not found/ShellEx error" is a quirk of *umu* itself when running just `createprefix` as the argument, so that's not in itself a problem. Is that the full CLI output?

I also don't recall ever seeing "UMU-Latest/UMU-Proton-9.0" entries pop up in that list. Some more system info would be appreciated (as well as what Qt version is shown in Nero's *About* dialog).

Unfortunately, on either of my setups available, I have not been able to reproduce such an issue.

> Nero's own dir "~/.local/share/Nero-UMU/compatibilitytools.d" does not exist. Not sure if thats supposed to be or if that dir should have been created when starting Nero but i just wanted to point it out

Indeed, Steam's directory takes priority and the Nero fallback directory is not created in that instance, so that's also not an issue.

**Comment by TimeFreeze1337** [comment]
Yes thats the full CLI output. 

QT version is: 

![Screenshot_20241206_105636](https://github.com/user-attachments/assets/18e2a60a-6c75-4d1f-8584-ee4d4e667d2d)


Some more System Infos:
![Screenshot_20241206_105923](https://github.com/user-attachments/assets/d8074e14-b51f-4672-861a-652cf605e829)


umu-launcher is installed directly from the Arch repos.
Nero-umu is also up to date built via the AUR.

I'll include a video maybe it helps a bit:

https://github.com/user-attachments/assets/5b2f6834-7b42-4cea-86c6-f134e732d6ae

**Comment by SeongGino** [comment]
Ah, I see!

So, long story short, I forced my EOS install to also use Qt6 (because this whole time it INSISTED on using Qt5, no heckin idea why), and when it's built with Qt 6.8.1 *now* I can reproduce this issue.

So somewhere along the lines between Qt 6.4 and 6.8, either getting directory info or the configuration file for the prefix got borked and is causing this issue.

this is pretty embarrassing, but I'll have a fix shortly :sweat:

**Comment by SeongGino** [comment]
Yeah so I don't know why pushbuttons - and *only* when accessed in the two/three functions that it was - add an ampersand, but the referenced commit should resolve this issue.
Far as I can tell, Nero works fine now with Qt 6.8 on Arch, but do confirm if there are any issues on your end please.

**Comment by TimeFreeze1337** [comment]
Yep seems to be fixed now! Created a few prefixes and they all work just fine now. The icon is also now there and the about page is now also displayed correctly.

Looks good now! I think its safe to say that you can push the update to the AUR as well now.

**Comment by SeongGino** [comment]
Updated AUR package! Let us never speak of this again :sweat_smile:
